title: Using ROS 2 Humble on Windows with WSL
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-feed
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: jekyll/minima
minima:
  skin: dark
header_pages: ['']
author: Grayson Arendt
